### ISSUE TITLE
weights 

### ISSUE THREAD

**Issue by zk2ly** [rekon/Smoke-semantic-segmentation#4]
i use your seg_model_weights.best.hdf5  in unet
but it show
"You are trying to load a weight file containing 20 layers into a model with 24 layers."
why?

**Comment by rekon** [comment]
@zk2ly The seg_model_weights.best.hdf5 was for model which had the following structure:
- The **X** in `layers.Conv2D(**X**, (3, 3), activation='relu', padding='same')` increased as:
  - 8 -> 16 -> 32 -> 64 -> 128 -> 64 -> 32 -> 16 -> 8 [as it should happen in encoder-decoder]
  - As a fix I will update the **seg_model_weights.best.hdf5** weights. These may not be the best since I am limited by input dataset and computational resources and it can be definitely improved

**Comment by rekon** [comment]
A visualization of previous weights (24 layers) by [netron](https://netron.app/)
![seg_model_weights best hdf5](https://user-images.githubusercontent.com/14028736/103480082-2735d680-4df8-11eb-996e-0d379391ae7b.png)

**Comment by rekon** [comment]
Also **seg_model_weights.best.hdf5** is for Unet model, not for Linknet, just FYI
